name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: docker build -t logger .

      - name: Run Docker container
        run: |
          mkdir -p logs
          printf "text1\ntext2\ntext3\n" | docker run -i -v "$(pwd)/logs:/home/logs" logger

      - name: Check log file
        run: cat logs/log.txt
